import { CorrectChecker, WordleChecker } from './checkers';

/*
 * Do not edit this file.
 */
export class CheckerFactory {
  public createChecker(answer: string): WordleChecker {
    return new CorrectChecker(answer);
  }
}
